#############################
- id: load_on
  alias: "Turn on load"
  trigger:
    platform: state
    entity_id: input_select.power_options
    to: "Turn on load"
  action:
    service: script.turn_on
    entity_id: script.load_on  
- id: load_off
  alias: "Turn off load"
  trigger:
    platform: state
    entity_id: input_select.power_options
    to: "Turn off load"
  action:
    service: script.turn_on
    entity_id: script.load_off
- id: shutdown_stayoff
  alias: "Shutdown remain off"
  trigger:
    platform: state
    entity_id: input_select.power_options
    to: "Shutdown remain off"
  action:
    service: script.turn_on
    entity_id: script.shutdown_stayoff  
- id: shutdown_stop
  alias: "Stop shutdown"
  trigger:
    platform: state
    entity_id: input_select.power_options
    to: "Stop shutdown"
  action:
    service: script.turn_on
    entity_id: script.shutdown_stop
- id: beeper_mute
  alias: "Beeper mute"
  trigger:
    platform: state
    entity_id: input_select.beeper_options
    to: "Beeper mute"
  action:
    service: script.turn_on
    entity_id: script.beeper_mute
- id: beeper_disable
  alias: "Beeper disable"
  trigger:
    platform: state
    entity_id: input_select.beeper_options
    to: "Beeper disable"
  action:
    service: script.turn_on
    entity_id: script.beeper_disable  
- id: beeper_enable
  alias: "Beeper enable"
  trigger:
    platform: state
    entity_id: input_select.beeper_options
    to: "Beeper enable"
  action:
    service: script.turn_on
    entity_id: script.beeper_enable
- id: initiate_selftest_quick
  alias: "Quick battery test"
  trigger:
    platform: state
    entity_id: input_select.test_options
    to: "Quick battery test"
  action:
    service: script.turn_on
    entity_id: script.initiate_selftest_quick
- id: initiate_selftest_deep
  alias: "Deep battery test"
  trigger:
    platform: state
    entity_id: input_select.test_options
    to: "Deep battery test"
  action:
    service: script.turn_on
    entity_id: script.initiate_selftest_deep 
- id: initiate_selftest_stop
  alias: "Stop battery test"
  trigger:
    platform: state
    entity_id: input_select.test_options
    to: "Stop battery test"
  action:
    service: script.turn_on
    entity_id: script.initiate_selftest_stop
- id: initiate_paneltest_start
  alias: "Start panel test"
  trigger:
    platform: state
    entity_id: input_select.test_options
    to: "Start panel test"
  action:
    service: script.turn_on
    entity_id: script.initiate_paneltest_start 
- id: initiate_paneltest_stop
  alias: "Stop panel test"
  trigger:
    platform: state
    entity_id: input_select.test_options
    to: "Stop panel test"
  action:
    service: script.turn_on
    entity_id: script.initiate_paneltest_stop
#####################################
- id: vis_info1
  alias: Information1
  trigger:
    - platform: state
      entity_id: input_select.info_options1
    - platform: homeassistant
      event: start
  action:
    service: script.group_visibility1
    data:
      entity_id: group.information1
      cond: input_select.info_options1
      visible_state: "Visable"
- id: vis_det1
  alias: Details1
  trigger:
    - platform: state
      entity_id: input_select.details1
    - platform: homeassistant
      event: start
  action:
    service: script.group_visdet1
    data:
      entity_id: group.details1
      cond: input_select.details1
      visible_state: "Visable"
- id: vis_det2
  alias: Details2
  trigger:
    - platform: state
      entity_id: input_select.details2
    - platform: homeassistant
      event: start
  action:
    service: script.group_visdet2
    data:
      entity_id: group.details2
      cond: input_select.details2
      visible_state: 'Visable'
- id: vis_info2
  alias: Information2
  trigger:
    - platform: state
      entity_id: input_select.info_options2
    - platform: homeassistant
      event: start
  action:
    service: script.group_visibility2
    data:
      entity_id: group.information2
      cond: input_select.info_options2
      visible_state: 'Visable'
- id: vis_opt2
  alias: Options2
  trigger:
    - platform: state
      entity_id: input_select.options2
    - platform: homeassistant
      event: start
  action:
    service: script.group_visibilityopt2
    data:
      entity_id: group.options2
      cond: input_select.options2
      visible_state: 'Visable'
######################################
- id: vis_detcharge1
  alias: DetailsCharge1
  trigger:
    platform: state
    entity_id: sensor.UPS1_battery_charge
    from: "100"
  action:
      service: input_select.select_option
      data:
        entity_id: input_select.details1
        option: "Visable"
- id: vis_detcharge2
  alias: DetailsCharge2
  trigger:
    platform: state
    entity_id: sensor.UPS2_battery_charge
    from: "100"
  action:
      service: input_select.select_option
      data:
        entity_id: input_select.details2
        option: "Visable"
#####################################


