###### Configuration ########
homeassistant:
  name: remboart
  latitude: !secret homeassistant_lat
  longitude: !secret homeassistant_long
  elevation: -2
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
group: !include groups.yaml
zone: !include zones.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
automation: !include automations.yaml
frontend:
config:
http:
  api_password: pass
updater:
  name: updater
discovery:
conversation:
history:
logbook:
sun:
  name: sun
###### APC SmartUPS ########
shell_command:
  beeper_disable: upscmd -u admin -p pass smartups@192.168.i.p beeper.disable
  beeper_enable: upscmd -u admin -p pass smartups@192.168.i.p beeper.enable
  initiate_selftest_quick: upscmd -u admin -p pass smartups@192.168.i.p test.battery.start.quick
  initiate_selftest_deep: upscmd -u admin -p pass smartups@192.168.i.p test.battery.start.deep
  initiate_selftest_stop: upscmd -u admin -p pass smartups@192.168.i.p test.battery.stop
  initiate_paneltest_start: upscmd -u admin -p pass smartups@192.168.i.p test.panel.start
  initiate_paneltest_stop: upscmd -u admin -p pass smartups@192.168.i.p test.panel.stop
  beeper_mute: upscmd -u admin -p pass smartups@192.168.i.p beeper.mute
  load_on: upscmd -u admin -p pass smartups@192.168.i.p load.on
  load_off: upscmd -u admin -p pass smartups@192.168.i.p load.off
  shutdown_stayoff: upscmd -u admin -p pass smartups@192.168.i.p shutdown.stayoff
  shutdown_stop: upscmd -u admin -p pass smartups@192.168.i.p shutdown.stop
input_select:
  beeper_options:
    name: Beeper Options
    options:
     - "Beeper enable"
     - "Beeper mute"
     - "Beeper disable"
    initial: "Beeper enable"
    icon: mdi:volume-low
  test_options:
    name: Test Options
    options:
     - "Stop battery test"
     - "Quick battery test"
     - "Deep battery test"
     - "Start panel test"
#     - "Stop panel test"
    initial: "Stop battery test"
    icon: mdi:checkbox-marked
  power_options:
    name: Power Options
    options:
     - "Turn on load"
     - "Turn off load"
#     - "Shutdown remain off"
     - "Stop shutdown"
    initial: "Stop shutdown"
    icon: mdi:power
#######################
###### Weblinks #######
weblink:
  entities:
    - name: Router
      url: http://192.168.i.p  # your router
#######################
