###### Configuration ########
homeassistant:
  name: Home
  latitude: !secret homeassistant_lat
  longitude: !secret homeassistant_long
  elevation:  !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_timezone
  customize: !include customize.yaml
group: !include groups.yaml
zone: !include zones.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
automation: !include automations.yaml
frontend:
config:
http:
  api_password: !secret http_password
updater:
  name: updater
discovery:
conversation:
history:
logbook:
sun:
  name: sun
###### UPS ########
shell_command:
  beeper_disable: !secret beeper_disable
  beeper_enable: !secret beeper_enable
  beeper_mute: !secret beeper_mute
  initiate_selftest_quick: !secret initiate_selftest_quick
  initiate_selftest_deep: !secret initiate_selftest_deep
  initiate_selftest_stop: !secret initiate_selftest_stop
  initiate_paneltest_start: !secret initiate_paneltest_start
  initiate_paneltest_stop: !secret initiate_paneltest_stop
  load_on: !secret load_on
  load_off: !secret load_off
  shutdown_stayoff: !secret shutdown_stayoff
  shutdown_stop: !secret shutdown_stop
input_select:
  options2:
    name: UPS2 Options
    options:
     - "Visible"
     - "Hide"
    initial: "Hide"
  info2:
    name: UPS2 Information
    options:
     - "Visible"
     - "Hide"
    initial: "Hide"
  info1:
    name: UPS1 Information
    options:
     - "Visible"
     - "Hide"
    initial: "Hide"
  details2:
    name: UPS2 Details
    options:
     - "Visible"
     - "Hide"
    initial: "Hide"
  details1:
    name: UPS1 Details
    options:
     - "Visible"
     - "Hide"
    initial: "Hide"
  beeper_options:
    name: Beeper Options
    options:
     - "Beeper enable"
     - "Beeper mute"
     - "Beeper disable"
    initial: "Beeper enable"
  test_options:
    name: Test Options
    options:
     - "Stop battery test"
#     - "Stop panel test"
     - "Quick battery test"
     - "Deep battery test"
     - "Start panel test"
    initial: "Stop battery test"
  power_options:
    name: Power Options
    options:
     - "Turn on load"
     - "Turn off load"
#     - "Shutdown remain off"
     - "Stop shutdown"
    initial: "Stop shutdown"
#######################
###### Weblinks #######
weblink:
  entities:
    - name: Router
      url: !secret router_ip
#######################

