###### NUT #########
- platform: nut
  name: UPS1
  host: !secret ip_ups1
  port: 3493
  alias: UPS1
  username: !secret nutuser_ups1
  password: !secret nutpass_ups1
  resources:
    - ups.status
    - battery.charge
    - battery.runtime
    - battery.voltage
    - ups.mfr
    - ups.model
    - ups.serial
- platform: nut
  name: UPS2
  host: !secret ip_ups2
  port: 3493
  alias: UPS2
  username: !secret nutuser_ups2
  password: !secret nutpass_ups2
  resources:
    - ups.status
    - battery.charge
    - battery.runtime
    - battery.voltage
    - ups.mfr
    - ups.model
    - ups.serial
    - input.voltage
    - ups.beeper.status
    - ups.test.result
    - battery.temperature
######## Weather ######
- platform: yr
  monitored_conditions:
    - symbol
  name: yr
####### System ########
- platform: cpuspeed
  name: CPU
- platform: systemmonitor
  name: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: ipv6_address
      arg: eth0
    - type: last_boot
    - type: since_last_boot
- platform: command_line
  name: CPUtemp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
- platform: time_date
  name: klok
  display_options:
    - time
    - date
###############
